--A nyilak jelölik az okot hogy miért pont így van
--1
CREATE TABLE SZEMÉLYEK(
 SZEMELY_SZAM INT PRIMARY KEY
);

CREATE TABLE AUTÓK(
 RSZ INT PRIMARY KEY,
 F_SZ_SZAM INT REFERENCES SZEMÉLYEK(SZEMELY_SZAM)
);

--2
CREATE TABLE SZEMÉLYEK(
 SZEMELY_SZAM INT PRIMARY KEY
);

CREATE TABLE AUTÓK(
 RSZ INT PRIMARY KEY,
);

CREATE TABLE KAPCSOLAT(
 TULAJDONSAG VARCHAR(100),
 F_RSZ INT REFERENCES AUTÓK(RSZ),
 F_SZ_SZAM INT REFERENCES SZEMÉLYEK(SZEMELY_SZAM)
);

--3
CREATE TABLE SZEMÉLYEK(
 SZEMELY_SZAM INT PRIMARY KEY
);

CREATE TABLE TELEFONSZÁMOK(
 TELEFONSZAM VARCHAR2(10),
  F_SZ_SZAM INT REFERENCES SZEMÉLYEK(SZEMELY_SZAM)
);

--4
CREATE TABLE SZEMÉLYEK(
 SZEMELY_SZAM INT PRIMARY KEY
);

CREATE TABLE AUTÓK(
 RSZ INT PRIMARY KEY,
);

CREATE TABLE KAPCSOLAT(
 F_RSZ INT REFERENCES AUTÓK(RSZ),
 F_SZ_SZAM INT REFERENCES SZEMÉLYEK(SZEMELY_SZAM)
);

--5
CREATE TABLE SZEMÉLYEK(
 SZEMELY_SZAM INT PRIMARY KEY
);

CREATE TABLE AUTÓK(
 RSZ INT PRIMARY KEY,
 F_SZ_SZAM INT REFERENCES SZEMÉLYEK(SZEMELY_SZAM)
);

CREATE TABLE HÁZAK(
 HELYRAJZI_SZAM INT PRIMARY KEY
);

CREATE TABLE TAKARÍTÁSOK_DÁTUMAI(
 ID INT PRIMARY KEY,
 DATUM DATE
);

CREATE TABLE KAPCSOLAT(
 F_SZ_SZAM INT REFERENCES SZEMÉLYEK(SZEMELY_SZAM),
 F_H_SZAM INT REFERENCES HÁZAK(HELYRAJZI_SZAM),
 F_ID INT REFERENCES TAKARÍTÁSOK_DÁTUMAI(ID)
);


--további fontos észrevétel: Az 
