CREATE TABLE EMBEREK(
    AZONOSITO INT PRIMARY KEY,
    NEV VARHCAR2(100)
);


CREATE TABLE GYAK7(
    SORSZAM INT PRIMARY KEY,
    TAGOK INT REFERENCES EMBEREK(AZONOSITO),
    AR INT NOT NULL,
    NEV VARHCAR2(100)
);



INSERT INTO GYAK7(SORSZAM,TAGOK,AR,NEV) VALUES(1,1,2300,'GYAK1');
INSERT INTO GYAK7(SORSZAM,TAGOK,AR,NEV) VALUES(2,1,2300,'GYAK2');
INSERT INTO GYAK7(SORSZAM,TAGOK,AR,NEV) VALUES(3,2,2300,'GYAK3');

SELECT * FROM GYAK7

UPDATE GYAK7 SET AR=1000, NEV='GYAK';

UPDATE GYAK7 SET AR=3000, NEV='GYAK1.1', TAGOK=2 WHERE AR<>1000;

UPDATE GYAK7 SET AR=2342 WHERE NEV LIKE 'GYAK';

DELETE FROM GYAK7 WHERE SORSZAM=3;

ALTER TABLE GYAK7 ADD NEPTUNKÓD VARCHAR2(6);

SELECT * FROM GYAK7

UPDATE GYAK7 SET NEPTUNKÓD='qwerty' WHERE SORSZAM=1;
SELECT * FROM GYAK7

UPDATE GYAK7 SET NEPTUNKÓD='ASDFGH' WHERE SORSZAM=2;

SELECT * FROM GYAK7

ALTER TABLE GYAK7 MODIFY NEPTUNKÓD CHECK(LENGTH(NEPTUNKÓD)>5);

INSERT INTO GYAK7 VALUES(3,1,2000,'GYAK3','QWEQWE');

TO_DATE(<formátum>,<formátumnak megfelelő dátum>);
